# Generated by Django 5.2 on 2025-04-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_telefono_remove_usuario_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='tipo_usuario',
        ),
    ]
