# Generated by Django 5.2 on 2025-04-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_rol_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='whatsapp',
            new_name='telefono',
        ),
    ]
